application: k2onepiece
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: media/favicon.ico
  upload: media/favicon.ico
  mime_type: image/x-icon

- url: /apple-touch-icon.png
  static_files: media/apple-touch-icon.png
  upload: media/apple-touch-icon.png

- url: /robots.txt
  static_files: media/robots.txt
  upload: media/robots.txt

- url: /crossdomain.xml
  static_files: media/crossdomain.xml
  upload: media/crossdomain.xml

- url: /humans.txt
  static_files: media/humans.txt
  upload: media/humans.txt

- url: /media
  static_dir: media

- url: /_generated_media
  static_dir: _generated_media

- url: /_media
  static_dir: kay/media

- url: /_kay/.*
  script: kay/main.py
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: kay/main.py
  login: admin

- url: /_ah/test.*
  script: kay/ext/testutils/gaeunit.py
  login: admin

- url: /.*
  script: kay/main.py

skip_files: |
  ^(.*/)?(
  (_backup/.*)|
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.po)|
  (.*\.pot)|
  (\..*)|
  (app\.yaml\.sample)|
  (index\.yaml\.sample)|
  (cron\.yaml\.sample)|
  (manage\.py)|
  (TODO)|
  (TODO\.pdf)|
  (README)|
  (README\.pdf)|
  (LICENSE)|
  (gaema-LICENSE)|
  (kay\/docs\/.*)|
  (kay\/management\/.*)|
  (kay\/lib\/babel\/localedata\/.*)|
  )$

